name: Update substack

on:
  workflow_dispatch:
  # schedule:
  #   # https://crontab.guru
  #   - cron: '00 */8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      - name: Install requirements
        run: pip install -r uasubstack/requirements.txt
      - name: Parse rss feeds
        run: |
          cd uasubstack
          python build_feed.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: "github_actions"
          message: '📪 Updated substack registry with new posts'
