name: Update substack

on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru
    - cron: "00 01 * * *"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install requirements
        run: |
          cd uasubstack
          rm -rf .venv
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      - name: Parse rss feeds
        run: |
          cd uasubstack
          source .venv/bin/activate
          python build_feed.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: "github_actions"
          message: "📪 Updated substack registry with new posts"
